### ISSUE TITLE
Indention

### ISSUE THREAD

**Issue by sindresorhus** [welovewordpress/SublimeHtmlTidy#3]
Instead of having the option `htmltidy-indent-spaces`, you should instead respect the current indention setting in Sublime, if it's tabs or spaces, and in the case of spaces, how many.

**Comment by welovewordpress** [comment]
Thank you for all your feedback, @sindresorhus. I already fixed issue #4 and issue #5 while I actually should be doing other things... and spent too much time researching about upgrade messages and custom version numbers.

So I would greatly appreciate it if you could just post those two lines of python that will get me the current indention settings in Sublime and I shall implement it in no time. Or send a pull request, of course. 

Thank you in advance.

**Comment by welovewordpress** [comment]
@sindresorhus Ok, the plugin now respects the current views indentation settings.

Actually, Tidy itself always outputs spaces and never tabs, so it converts spaces to tabs afterwards.

The option in the settings file will be removed.
