### ISSUE TITLE
Only return body if I select the whole HTML when running tidy command

### ISSUE THREAD

**Issue by longhua** [welovewordpress/SublimeHtmlTidy#34]
I use default settings and the original HTML is as follow:

``` html
<!DOCTYPE html>
<html>
<head>
 <title>Title</title>
</head>
<body>
<h1>heading 1</h1>
<p>
paragraph 1
</p>
</body>
</html>
```

I select the whole document and run tidy command. Then I get the following text:

```
<h1>
    heading 1
</h1>
<p>
    paragraph 1
</p>
```

It only returns the content of HTML body.

**Comment by welovewordpress** [comment]
You're not supposed to select the whole document before calling Tidy - either select some HTML snippet, or don't select anything if you want the whole document to be processed.
