### ISSUE TITLE
Line wrapping should be off by default

### ISSUE THREAD

**Issue by sindresorhus** [welovewordpress/SublimeHtmlTidy#5]
Currently the line wrapping `htmltidy-wrap` is set to 100 by default. Most people don't want this, since it's a pretty crude hard wrapping and can break stuff. I recommend you change it to be off by default. Most devs have a soft line wrapping in sublime anyway.

**Comment by welovewordpress** [comment]
Thank you for bringing this to my attention. It's fixed by now.
